<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="Test_Class-20210405105119" tests="11" time="0.172">
	<testcase classname="Test_Class" name="test_Commom_Utils" time="0.002"/>
	<testcase classname="Test_Class" name="test_Google_Babynames" time="0.004"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_1" time="0.005"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_2" time="0.009"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_3" time="0.022"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_4" time="0.026"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_5" time="0.029"/>
	<testcase classname="Test_Class" name="test_Google_Exercise_6" time="0.018"/>
	<testcase classname="Test_Class" name="test_Python_Pytest" time="0.029"/>
	<testcase classname="Test_Class" name="test_Python_OOP" time="0.029">
		<error message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/sarth/Python_Exercises_Test_Jenkins/Test_Wrapper.py", line 69, in test_Python_OOP
    assert sum == 10
AssertionError
]]>		</error>
	</testcase>
	<testcase classname="Test_Class" name="test_to_fail" time="0.000">
		<error message="'Test_Class' object does not support indexing" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/sarth/Python_Exercises_Test_Jenkins/Test_Wrapper.py", line 21, in test_to_fail
    assert tuple_data[4]['size'] == 1023 #Pass
TypeError: 'Test_Class' object does not support indexing
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[...............Common Utils Test Completed................
...............Google Test Completed................
...............Pytest Test Completed................
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
